version: '3.4'

services:
  my-serve-api:
    image: alenalex/myserve-http-api:master
    restart: on-failure
    environment:
      - ASPNETCORE_URLS=http://*:80
    volumes:
      - /home/my-serve/api/appsettings.json:/app/appsettings.json
      - /home/my-serve/api/Logs/:/app/Logs/