services:
  my-serve-api:
    image: alenalex/myserve-http-api:master
    restart: on-failure
    environment:
      - ASPNETCORE_URLS=http://*:80
    volumes:
      - /home/my-serve/api/appsettings.json:/app/appsettings.json
      - /home/my-serve/api/Logs/:/app/Logs/
    ports:
      - "45012:80"
  my-serve-worker-message-consumer:
    image: alenalex/myserve-worker-message-consumer:master
    restart: on-failure
    volumes:
      - /home/my-serve/worker-message-consumer/appsettings.json:/app/appsettings.json
      - /home/my-serve/worker-message-consumer/Logs/:/app/Logs/    